title: The Big Hong
email: 15901423703@163.com
description: > # this means to ignore newlines until "baseurl:"
  iOS developer is who I am! You can call me Hong! This blog is just for my persional using. If there is some 
  mistake in my writting,take it easy! I write blog just for fun now. I don't like to write blog for a long time too.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ahongkong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: noRegister
github_username:  AHongKong

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

gems: [jekyll-paginate]

exclude:
  - Gemfile
  - Gemfile.lock
exclude: [vendor]

# blog setting
paginate: 5
paginate_path: "page:num"
